name: Static Code Analysis

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - .github/workflows/sca.yml
  schedule:
    - cron: "0 0 * * 2"
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: read
  security-events: write

jobs:
  docker_static_analysis:
    name: Docker Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Lint Dockerfile using Hadolint and output SARIF
      - name: Dockerfile Linting with Hadolint
        run: |
          docker run --rm -i hadolint/hadolint hadolint -f sarif - < Dockerfile > hadolint.sarif
        continue-on-error: true

      # Upload Hadolint SARIF file to GitHub Code Scanning
      - name: Upload Hadolint SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint.sarif

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker Image
        run: docker buildx build --load --platform linux/amd64 -t sample-php-app:latest .

      # Perform vulnerability scanning with Trivy and output SARIF
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: sample-php-app:latest
          format: sarif
          output: trivy.sarif

      # Upload Trivy SARIF file to GitHub Code Scanning
      - name: Upload Trivy SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif

  helm_linting:
    name: Helm Linting and Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Lint Helm chart and output SARIF file
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: config
          scan-ref: ./helm
          format: sarif
          output: helm.sarif

      # Upload Helm Lint SARIF to GitHub Code Scanning
      - name: Upload Helm Lint SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: helm.sarif

      # Install kube-score
      - name: Install kube-score
        run: |
          curl -L -o kube-score https://github.com/zegl/kube-score/releases/download/v1.18.0/kube-score_1.18.0_linux_$(uname -p)64
          chmod +x kube-score
          sudo mv kube-score /usr/local/bin/

      # Run kube-score to check Kubernetes resources generated by the Helm chart and output SARIF file
      - name: Kube-score Helm chart analysis
        run: |
          helm template sample-php-app ./helm | kube-score score -o sarif - > kube-score.sarif
        continue-on-error: true

      # Upload Kube-score SARIF to GitHub Code Scanning
      - name: Upload Kube-score SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kube-score.sarif

  terraform_scanning:
    name: Terraform Linting and Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Lint Helm chart and output SARIF file
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: config
          scan-ref: ./terraform
          format: sarif
          output: terraform.sarif

      # Upload terraform scanning SARIF to GitHub Code Scanning
      - name: Upload terraform SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: terraform.sarif

  php_static_analysis:
    name: PHP Static Code Analysis
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./php

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: mbstring, xml, intl

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Run PHPStan
        continue-on-error: true
        run: ./vendor/bin/phpstan analyze --error-format=sarif > phpstan-results.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./php/phpstan-results.sarif
          wait-for-processing: true
