name: Terraform Deployment

on:
  push:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/terraform.yml
  pull_request_target:
    branches:
      - main
    paths:
      - terraform/**
      - .github/workflows/terraform.yml
  workflow_dispatch: # Manual trigger

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    defaults:
      run:
        working-directory: terraform

    # Define environment variables for AWS and Terraform
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-west-2
      TF_VAR_region: us-west-2

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Initialize the Terraform configuration
      - name: Terraform Init
        run: terraform init

      # Validate the Terraform configuration to catch any errors
      - name: Terraform Validate
        run: terraform validate

      # Plan the Terraform deployment
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Optionally add an approval step for manual deployment
      - name: Terraform Plan Approval
        if: github.event_name == 'pull_request'
        uses: hmarr/auto-approve-action@v4
        with:
          review-message: Terraform plan is ready for deployment
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Apply the Terraform changes
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
